### ISSUE TITLE
Roblox Studio and Player don't respect `renderer` setting.

### ISSUE THREAD

**Issue by xTrayambak** [vinegarhq/vinegar#172]
Recently, Roblox Studio stopped using OpenGL and instead defaults to Vulkan, even though I have told it to use OpenGL. This wasn't the case for Roblox Player, but recently, it has started to do the same. Here is my config:
```toml
launcher = ""
# wineroot = "/home/tray/.var/app/io.vinegarhq.Vinegar/data/wine-ge"

[env]
WINEFSYNC = "1"

[player]
renderer = "OpenGL"
channel = "zcanary"
dxvk = false

[studio]
renderer = "OpenGL"
channel = "zcanary"
dxvk = false
```
I know that it is using Vulkan as I get a few warnings in the terminal when I launch either of them about Vulkan.
