### ISSUE TITLE
environment variables on [player.env] affects Studio

### ISSUE THREAD

**Issue by Eggflaw** [vinegarhq/vinegar#265]
Studio has mangohud enabled even though I only specified it specified for the Player client

Distro: Arch Linux
Kernel: 6.5.9-arch2-1
Wine version: wine-ge-8-18
Install method: AUR

My current configuration:
```toml
wineroot = "/home/eggflaw/.local/share/lutris/runners/wine/wine-ge-8-18-x86_64"

[player]
dxvk = true

[player.env]
MANGOHUD = "1"
DXVK_HUD = "0"

[studio]
renderer = "D3D11"
auto_kill_prefix = true
```

### Studio with `MANGOHUD` enabled on `[player.env]`
Menu:
![menu_mangohud_aur](https://github.com/vinegarhq/vinegar/assets/108559753/fda6f44c-7926-475b-aa4e-39704bbdfa10)

Baseplate:
![baseplate_mangohud_aur](https://github.com/vinegarhq/vinegar/assets/108559753/65a69e4a-42ec-44a4-9ea9-4a075274a353)

### Studio with `DXVK_HUD` enabled on `[player.env]`
```toml
[player.env]
MANGOHUD = "0"
DXVK_HUD = "1"
```
Menu:
![menu_dxvk_hud_aur](https://github.com/vinegarhq/vinegar/assets/108559753/3b9fea69-a865-47de-ae8c-972e170d9474)

Baseplate:
![baseplate_dxvkhud_aur](https://github.com/vinegarhq/vinegar/assets/108559753/05f133d5-8164-43fd-8b58-bc817332854e)
